[project]
name = "shapetune"
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
description = "Fitting Structural Parameters to SHAPE Data"
platforms = ["linux-64"]
readme = "README.md"
version = "0.1.0"

[dependencies]
python = ">=3.9.0"
numpy = ">=2.1.0,<3"
scipy = ">=1.14.0,<2"
uv = ">=0.2.37,<0.3"
jax = ">=0.4.31,<0.5"
jaxlib = ">=0.4.31,<0.5"
jupyter_core = ">=5.7.2,<6"
jupyter_server = ">=2.14.2,<3"
pip = ">=23.0.0,<25"

[pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }
